version: '2'
services:
  db:
    build: ./db
    container_name: godorp_db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    container_name: godorp_api
    volumes:
      - ./api:/go/src/api
    ports:
      - "5000:8080"
    links:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV}
    container_name: godorp_frontend
    volumes:
      - ./frontend/src:/frontend/src 
    ports:
      - "3000:3000"
